@startuml

title __CORE's Class Diagram__\n

  package itesm.cem.mx {
    class Enemigo {
    }
  }
  

  package itesm.cem.mx {
    enum EstadoJuego {
    }
  }
  

  package itesm.cem.mx {
    class Objeto {
    }
  }
  

  package itesm.cem.mx {
    abstract class Pantalla {
    }
  }
  

  package itesm.cem.mx {
    class PantallaCreditos {
    }
  }
  

  package itesm.cem.mx {
    class PantallaExtras {
    }
  }
  

  package itesm.cem.mx {
    class PantallaGameOver {
    }
  }
  

  package itesm.cem.mx {
    class PantallaInicio {
    }
  }
  

  package itesm.cem.mx {
    class PantallaJuego {
    }
  }
  

  package itesm.cem.mx {
    class PantallaMapa {
    }
  }
  

  package itesm.cem.mx {
    class PantallaMenu {
    }
  }
  

  package itesm.cem.mx {
    class PantallaNivel {
    }
  }
  

  package itesm.cem.mx {
    class PantallaOpciones {
    }
  }
  

  package itesm.cem.mx {
    class Personaje {
    }
  }
  

  Enemigo -up-|> Objeto
  Pantalla -up-|> Screen
  PantallaCreditos -up-|> Pantalla
  PantallaCreditos o-- PantallaInicio : pantallaInicio
  PantallaExtras -up-|> Pantalla
  PantallaExtras o-- PantallaInicio : pantallaInicio
  PantallaGameOver -up-|> Pantalla
  PantallaGameOver o-- PantallaInicio : pantallaInicio
  PantallaInicio -up-|> Game
  PantallaJuego -up-|> Pantalla
  PantallaJuego o-- PantallaInicio : pantallaInicio
  PantallaMapa -up-|> Pantalla
  PantallaMapa o-- PantallaInicio : pantallaInicio
  PantallaMapa o-- EstadoJuego : estado
  PantallaMapa o-- EscenaPausa : escenaPausa
  PantallaMapa o-- Personaje : ivan
  PantallaMenu -up-|> Pantalla
  PantallaMenu o-- PantallaInicio : pantallaInicio
  PantallaNivel -up-|> Pantalla
  PantallaOpciones -up-|> Pantalla
  PantallaOpciones o-- PantallaInicio : pantallaInicio
  Personaje -up-|> Objeto
  Personaje o-- EstadoMovimento : estadoMover


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
